### ISSUE TITLE
rebuild for .net 4.5.2

### ISSUE THREAD

**Issue by apobekiaris** [71/Ryder#6]
I tried to target 4.5.2 but failed, do u thin that is possible? or maybe there is some old version of this project?

**Comment by apobekiaris** [comment]
never mind i manage to target 4.6.1 and works perfect!

Keep up the amazing work.

**Comment by 71** [comment]
Hey there,

Sorry, but Ryder is only available for .NET Standard 1.3+, and therefore .NET Framework 4.6+.

**Update**: I started working on .NET Framework 4.5 support a few minutes before you closed this issue, and it should now work, in case staying in 4.5 is something you'd rather do.

**Comment by apobekiaris** [comment]
>I started working on .NET Framework 4.5 support a few minutes before you closed this issue, and it should now work, in case staying in 4.5 is something you'd rather do.

great news!

The way I did it is forked and add an additional target to 461 is there a way to use the nuget package without rebuilding?

**Comment by 71** [comment]
I updated the NuGet package to support .NET Framework 4.5 and up directly, so you can just update Ryder's version to 0.8.0!

**Comment by apobekiaris** [comment]
with 0.7.0 when I added the nuget package into a 461 module dll deep in chain (meaning the module is a submodule) and tried to run a Win front end project referencing the root submodule I got FileLoadException on System.Reflection.TypeExtensions and System.RunTime and if I try it on a web front end project I got for System.Reflection.TypeExtensions only.

I used a hacked to force the the copy of System.Reflection.TypeExtensions to the bin but could not do it for  System.Runtime as is not a 461 dependency.

all those problems went away when I manually rebuild adding a net461 target.

hope I make some sense.

**Comment by apobekiaris** [comment]
now my sub sub module only reference the Ryder.dll which in the same folder after build there are the System.Reflection.TypeExtensions, System.Runtime.InteropServices.RuntimeInformation. The front end projects have no references to ryder or its dependencies only to root module. 

this setup works fine for 461.

**Comment by 71** [comment]
Huh. I haven't touched the .NET Framework in a while, so I don't really see what could be happening here. Maybe .NET is confused because both .NET Standard 1.3 and .NET Framework 4.5 can work with .NET Framework 4.6.1? I don't really know, sorry. But since it does work I'll keep this closed for now.

**Comment by apobekiaris** [comment]
I updated to 0.8.0 and no dependencies issues, thanks!
